KLEE: Using STP solver backend
KLEE: ERROR: projeto.c:235: external call with symbolic argument: printf
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto.c:428: external call with symbolic argument: printf
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto.c:432: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto.c:432: external call with symbolic argument: printf
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto.c:142: external call with symbolic argument: printf
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto.c:146: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto.c:146: memory error: object read only
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto.c:186: external call with symbolic argument: printf
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto.c:192: memory error: object read only
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto.c:192: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto.c:314: external call with symbolic argument: printf
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto.c:320: external call with symbolic argument: printf
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto.c:324: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto.c:330: memory error: out of bound pointer
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto.c:326: external call with symbolic argument: printf
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto.c:488: external call with symbolic argument: printf
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: projeto.c:492: external call with symbolic argument: printf
KLEE: NOTE: now ignoring this error at this location
